# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: install npm
      run: yarn install
    - name: build dist
      run: yarn build 
    - name:  copy config to dist
      run: cp nginx.conf Dockerfile dist/
    - name: build image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: 18790997531/destinycoreweb
        tags: latest
        path: /home/runner/work/destiny-admin-flow-umi/destiny-admin-flow-umi/dist
        dockerfile: /home/runner/work/destiny-admin-flow-umi/destiny-admin-flow-umi/Dockerfile
    - name: deploy to portainer
      uses: LGinC/portainer-stack-deploy@0.2
      with: 
        serverurl: http://1065.cloud:8862
        username: ${{ secrets.PORTAINER_USERNAME }}
        password: ${{ secrets.PORTAINER_PASSWORD }}
        endpointId: 1
        stackname: destinyweb
        imagename: 18790997531/destinycoreweb:latest
        docker_compose: |
          version: "2"
          services:
            destinyapi:
              image:  18790997531/destinycoreweb
              container_name: DestinyFlowWEB_From_GithubAction             
              ports:
              - 7762:80
              environment: 
                TZ: Asia/Shanghai      
